import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        dir="ltr"
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-[600vh]`}
      >
        <header
          id="main-header"
          className=" h-[88px] lg:h-[110px] fixed w-full top-0 z-10 flex justify-between items-center px-10"
        >
          <img
            id="header-logo"
            src="https://areebe.com/wp-content/uploads/2025/02/Areeb-Logo-01-copy.png"
            alt="Slide Image"
            style={{
              width: "160px",
              visibility: "hidden",
            }}
          />
        </header>
        {children}
        {/* =========================================== */}
        <div>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe est
          voluptates eaque quae doloremque libero expedita magnam repudiandae.
          Itaque atque neque est aliquid rerum sed earum quidem, nobis quo
          dolorem!
        </div>
      </body>
    </html>
  );
}
